---
version: "3.8"
services:
  bot:
    image: "gregdan3/ilo-pi-toki-pona-taso:${VERSION:-latest}"
    build:
      context: "."
      dockerfile: "Dockerfile"
    environment:
      DISCORD_TOKEN: "${DISCORD_TOKEN}"
      LOG_LEVEL: "${LOG_LEVEL}"
      DEBUG_GUILDS: "${DEBUG_GUILDS}"
      DB_FILE: "${DB_FILE}"
    volumes:
      - ./userdata/:/project/userdata/
      - ./de421.bsp:/project/de421.bsp
    deploy:
      restart_policy:
        condition: "unless-stopped"
