[tool.pdm]

[project]
name = "tenpo"
version = "0.1.0"
description = ""
authors = [
  { name = "Gregory Danielson", email = "gregory.danielson3@gmail.com" },
]
dependencies = [
  "skyfield>=1.45",
  "py-cord>=2.4.0",
  "datetime>=5.0",
  "pytest>=7.2.2",
]
requires-python = ">=3.10"
license = { text = "MIT" }

[tool.pdm.dev-dependencies]
dev = [
    "black>=23.1.0",
    "isort~=5.9",
]

[tool.isort]
length_sort = "1"
profile = "black"
sections = "STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
import_heading_stdlib = "STL"
import_heading_thirdparty = "PDM"
import_heading_firstparty = "LOCAL"
import_heading_localfolder = "LOCAL"


[tool.pyright]
include = ["src/tenpo"]
exclude = ["**/__pycache__"]
ignore = []
defineConstant = { DEBUG = true }
stubPath = ""

reportMissingImports = true
reportMissingTypeStubs = false

pythonVersion = "3.10"
pythonPlatform = "Linux"

executionEnvironments = [{ root = "src/tenpo" }]
